# High-level job related parameters
HJOB:
  RANDOM_SEED: 1234
  PHASE: "aggregate_training"
  JOB_STRING: "test_agg"

# Dataset related parameters
DATA:
  DATASET: "DomainNet"
  DOMAIN_LIST: "clipart,infograph,painting,quickdraw,real"
  TARGET_DOMAINS: "sketch"
  DATA_SPLIT_DIR: "data/DomainNet/tv_0.9_splits/"
  HEAD_MODE: "single"

# Model related parameters
MODEL:
  BASE_MODEL: "alexnet"
  PARAM_INIT: "custom"
  USE_PRETRAINED: True
  NUM_CLASSES: 345

# Checkpoint related parameters
CKPT:
  STORAGE_DIR: "../DMG/"

# Dataloader related parameters
DATALOADER:
  BATCH_SIZE: 64
  DATA_SAMPLING_MODE: "uniform"

# Optimizer related parameters
OPTIM:
  OPTIMIZER: "Adam"
  LEARNING_RATE: 1e-4
  LEARNING_RATE_SCHEDULER: "invlr"
  LEARNING_RATE_DECAY_RATE: 0.1
  LEARNING_RATE_DECAY_MODE: "iter"
  LEARNING_RATE_DECAY_STEP: 1
  WEIGHT_DECAY: 0.0

# Epoch / Iteration related parameters
EP_IT:
  MAX_EPOCHS: 50
  LOG_INTERVAL: 50
  CKPT_STORE_INTERVAL: 2

# Process related parameters
PROCESS:
  USE_GPU: True
  NUM_WORKERS: 6